pepew/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('story1/', include('story1.urls')),
    path('story6/', include('story6.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
    path('', include('story4.urls')),
]

story6/urls.py
from django.urls import path

from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.index, name='index'),
    path('addevent/', views.addevent, name='addevent'),
    path('addperson/', views.addperson, name='addperson'),
    path('deleteevent/<int:event_id>', views.deleteevent, name='deleteevent'),
    path('editparticipant/<int:event_id>', views.editparticipant, name='editparticipant'),
    path('removeparticipant/<int:event_id>/<int:person_id>', views.removeparticipant, name='removeparticipant'),
    path('addparticipant/<int:event_id>/<int:person_id>', views.addparticipant, name='addparticipant'),
    path('deleteperson/<int:event_id>/<int:person_id>', views.deleteperson, name='deleteperson'),
]

story6/models.py
from django.db import models

# Create your models here.

class Person(models.Model):
    name = models.CharField(max_length=100)
    nickname = models.CharField(max_length=100)
    domicile = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Event(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    participant = models.ManyToManyField(Person, blank=True)

story6/forms.py
from django.forms import ModelForm
from .models import Event, Person

class EventForm(ModelForm):
    class Meta:
        model = Event
        fields = '__all__'

class PersonForm(ModelForm):
    class Meta:
        model = Person
        fields = '__all__'

story6/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect

from .models import Event, Person
from .forms import EventForm, PersonForm

# Create your views here.
def index(request):
    events = Event.objects.all()
    context = {'events':events}

    return render(request, 'story6/index.html', context)

def addevent(request):
    form = EventForm()
    context = {'form':form}

    if request.method == "POST":
        form = EventForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/story6/')

    return render(request, 'story6/addevent.html', context)

def addperson(request):
    form = PersonForm()
    context = {'form':form}

    if request.method == "POST":
        form = PersonForm(request.POST)

        if form.is_valid():
            form.save()

    return render(request, 'story6/addperson.html', context)

def deleteperson(request, event_id, person_id):
    person = Person.objects.get(id=person_id)
    person.delete()

    return redirect('/story6/editparticipant/' + str(event_id))

def deleteevent(request, event_id):
    event = Event.objects.get(id=event_id)
    event.delete()

    return redirect('/story6/')

def editparticipant(request, event_id):
    event = Event.objects.get(id=event_id)
    persons = Person.objects.exclude(id__in=event.participant.all())

    context = {'event':event, 'persons':persons}

    return render(request, 'story6/editparticipant.html', context)

def addparticipant(request, event_id, person_id):
    event = Event.objects.get(id=event_id)
    person = Person.objects.get(id=person_id)
    event.participant.add(person)

    return redirect('/story6/editparticipant/' + str(event_id))

def removeparticipant(request, event_id, person_id):
    event = Event.objects.get(id=event_id)
    person = Person.objects.get(id=person_id)
    event.participant.remove(person)

    return redirect('/story6/editparticipant/' + str(event_id))

story6/templates/story6/addevent.html
{% extends 'story4/template.html' %}

{% load static %}

{% block title %}Kevin Dharmawan - Course{% endblock title %}
{% block nav-story6 %}active{% endblock nav-story6 %}

{% block add-style %}
#id_name, #id_description, #id_participant {
    width: 400px;
}
{% endblock add-style %}

{% block content %}


<div class="container">
    <div class="row" style="height:80px;"></div>
    <div class="row justify-content-center">
        <h2 style="color: coral; padding: 30px;">add event</h2>
    </div>
    <div class="row justify-content-center">
        <div class="table-responsive-lg">
            <form action="" method="POST">
            <table class="table">
                <tbody>
                    {{ form.as_table }}
                    <tr>
                        <th></th>
                        <td>
                            {% csrf_token %}
                            <input class="btn btn-primary" type="submit" value="Add Event" style="padding-right: 50px; padding-left: 50px;">
                        </td>
                    </tr>
                </tbody>
            </table>
            </form>
        </div>
    </div>
    <div class="row" style="height: 80px;"></div>
</div>


{% endblock content %}

story6/templates/story6/addperson.html
{% extends 'story4/template.html' %}

{% load static %}

{% block title %}Kevin Dharmawan - Course{% endblock title %}
{% block nav-story6 %}active{% endblock nav-story6 %}

{% block add-style %}
#id_name, #id_nickname, #id_domicile {
    width: 400px;
}
{% endblock add-style %}

{% block content %}


<div class="container">
    <div class="row" style="height:150px;"></div>
    <div class="row justify-content-center">
        <h2 style="color: coral; padding: 30px;">add person</h2>
    </div>
    <div class="row justify-content-center">
        <div class="table-responsive-lg">
            <form action="" method="POST">
            <table class="table">
                <tbody>
                    {{ form.as_table }}
                    <tr>
                        <th></th>
                        <td>
                            {% csrf_token %}
                            <input class="btn btn-primary" type="submit" value="Add Person" style="padding-right: 70px; padding-left: 70px;">
                        </td>
                    </tr>
                </tbody>
            </table>
            </form>
        </div>
    </div>
    <div class="row" style="height: 150px;"></div>
</div>


{% endblock content %}

story6/templates/story6/editparticipant.html
{% extends 'story4/template.html' %}

{% load static %}

{% block title %}Kevin Dharmawan - Blog{% endblock title %}
{% block nav-story6 %}active{% endblock nav-story6 %}

{% block content %}

<div class="container">
    <center>
    <div class="row" style="height:150px;"></div>
    <div class="row justify-content-center">
        <h1 style="color: coral; padding: 30px;">manage participant</h1>
    </div>

    <div class="row">
        <div class="col">
            <table class="table table-hover" style="width: 700px;">
                <tbody>
        
                {% for person in persons %}
        
                    <tr>
                        <td style="width: 250px;">{{ person.name }}</td>
                        <td style="width: 200px;">{{ person.domicile }}</td>
                        <td>
                            <form action="/story6/addparticipant/{{ event.id }}/{{ person.id }}" method="POST" style="display: inline;">
                                {% csrf_token %}
                                <input class="btn btn-primary" type="submit" value="Add Participant" style="width: 100%;">
                            </form>
                        </td>
                        <td>
                            <form action="/story6/deleteperson/{{ event.id }}/{{ person.id }}" method="POST" style="display: inline;">
                                {% csrf_token %}
                                <input class="btn btn-danger" type="submit" value="Delete">
                            </form>
                        </td>
                    </tr>
        
                {% endfor %}

                {% for participant in event.participant.all %}

                    <tr>
                        <td style="width: 250px;">{{ participant.name }}</td>
                        <td style="width: 200px;">{{ participant.domicile }}</td>
                        <td>
                            <form action="/story6/removeparticipant/{{ event.id }}/{{ participant.id }}" method="POST" style="display: inline;">
                                {% csrf_token %}
                                <input class="btn btn-danger" type="submit" value="Remove Participant" style="width: 100%;">
                            </form>
                        </td>
                        <td>
                            <form action="/story6/deleteperson/{{ event.id }}/{{ person.id }}" method="POST" style="display: inline;">
                                {% csrf_token %}
                                <input class="btn btn-danger" type="submit" value="Delete">
                            </form>
                        </td>
                    </tr>

                {% endfor %}
        
                </tbody>
            </table>
        </div>
    </div>
    
    <div class="row justify-content-center">
        <a class="btn btn-success" style="padding-left: 50px; padding-right: 50px;" href= "{% url 'story6:addperson' %}">Add New Participant</a>
    </div>
    </center>
</div>

{% endblock content %}

story6/templates/story6/index.html
{% extends 'story4/template.html' %}

{% load static %}

{% block title %}Kevin Dharmawan - Blog{% endblock title %}
{% block nav-story6 %}active{% endblock nav-story6 %}

{% block content %}

<div class="container justify-content-center">
    <div class="row" style="height:100px;"></div>
    <div class="row justify-content-center">
        <h1 style="color: coral; padding: 30px;">events</h1>
    </div>

    {% if events %}

    <div class="row">
        <div class="col justify-content-center">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col" style="width: 200px;">Name</th>
                        <th scope="col">Description</th>
                        <th scope="col" style="width: 200px;">Participants</th>
                        <th scope="col">Edit</th>
                    </tr>
                </thead>
                <tbody>
        
                {% for event in events %}
        
                    <tr>
                        <td>{{ event.name }}</td>
                        <td>{{ event.description }}</td>
                        <td>
                            {% for person in event.participant.all %}
                            <p>{{ person.nickname }}</p>
                            {% endfor %}
                        </td>
                        <td>
                            <form action="/story6/editparticipant/{{ event.id }}" method="POST" style="display: inline;">
                                {% csrf_token %}
                                <input class="btn btn-primary" type="submit" value="Participants" style="width: 100%;">
                            </form>
                            <div style="height: 3px;"></div>
                            <form action="/story6/deleteevent/{{ event.id }}" method="POST" style="display: inline;">
                                {% csrf_token %}
                                <input class="btn btn-danger" type="submit" value="Delete" style="width: 100%;">
                            </form>
                        </td>
                    </tr>
        
                {% endfor %}
        
                </tbody>
            </table>
        </div>
    </div>

    {% else %}

    <div class="row justify-content-center">
        <h3>you don't have any event.</h3>
    </div>

    {% endif %}
    
    <div class="row justify-content-center">
        <a class="btn btn-success" style="padding-left: 50px; padding-right: 50px;" href= "{% url 'story6:addevent' %}">Add Event</a>
    </div>
    <div class="row" style="height:100px;"></div>
    
</div>

{% endblock content %}