pepew/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('story1/', include('story1.urls')),
    path('story6/', include('story6.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
    path('', include('story4.urls')),
]

story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns = [
    path('', views.index, name='index'),
]

story4/urls.py
from django.urls import path

from . import views

app_name = 'story4'

urlpatterns = [
    path('', views.index, name='index'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('blog/', views.blog, name='blog'),
    path('about/', views.about, name='about'),
    path('course/', views.course, name='course'),
    path('addcourse/', views.addcourse, name='addcourse'),
    path('detailcourse/<int:course_id>', views.detailcourse, name='detailcourse'),
    path('deletecourse/<int:course_id>', views.deletecourse, name='deletecourse'),
]

story6/urls.py
from django.urls import path

from . import views

app_name = 'story6'

urlpatterns = [
    path('', views.index, name='index'),
    path('addevent/', views.addevent, name='addevent'),
    path('addperson/', views.addperson, name='addperson'),
    path('deleteevent/<int:event_id>', views.deleteevent, name='deleteevent'),
    path('editparticipant/<int:event_id>', views.editparticipant, name='editparticipant'),
    path('removeparticipant/<int:event_id>/<int:person_id>', views.removeparticipant, name='removeparticipant'),
    path('addparticipant/<int:event_id>/<int:person_id>', views.addparticipant, name='addparticipant'),
    path('deleteperson/<int:event_id>/<int:person_id>', views.deleteperson, name='deleteperson'),
]

story8/urls.py
from django.urls import path

from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.index, name='index'),
    path('data/', views.data, name='data'),
]

story9/urls.py
from django.urls import path

from . import views

app_name = 'story9'

urlpatterns = [
    path('', views.index, name='index'),
    path('logout/', views.userlogout, name='logout'),
    path('register/', views.userregister, name='register'),
]

story4/models.py
from django.db import models

# Create your models here.

class Course(models.Model):
    DIFFICULTY = (
        ('EASY', 'EASY'),
        ('NORMAL', 'NORMAL'),
        ('HARD', 'HARD'),
        ('EXTREME', 'EXTREME'),
        ('INSANE', 'INSANE'),
        )

    YEAR = (
        ('2019/2020 - ODD', '2019/2020 - ODD'),
        ('2019/2020 - EVEN', '2019/2020 - EVEN'),
        ('2020/2021 - ODD', '2020/2021 - ODD'),
        )

    name = models.CharField(max_length=100)
    initial = models.CharField(max_length=10)
    lecturer = models.CharField(max_length=100)
    credit = models.IntegerField()
    difficulty = models.CharField(max_length=10, choices=DIFFICULTY)
    description = models.TextField()
    year = models.CharField(max_length=100, choices=YEAR)
    room = models.CharField(max_length=100)

story4/forms.py
from django.forms import ModelForm
from .models import Course

class CourseForm(ModelForm):
    class Meta:
        model = Course
        fields = '__all__'

story4/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect

from .models import Course
from .forms import CourseForm

# Create your views here.
def index(request):
    return render(request, 'story4/index.html')

def portfolio(request):
    return render(request, 'story4/portfolio.html')

def blog(request):
    return render(request, 'story4/blog.html')

def about(request):
    return render(request, 'story4/about.html')

def course(request):
    courses = Course.objects.all()
    context = {'courses':courses}

    return render(request, 'story4/course.html', context)

def detailcourse(request, course_id):
    course = Course.objects.get(id=course_id)
    context = {'course':course}

    return render(request, 'story4/detailcourse.html', context)

def addcourse(request):
    form = CourseForm()
    context = {'form':form}

    if request.method == "POST":
        form = CourseForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('/course/')

    return render(request, 'story4/addcourse.html', context)

def deletecourse(request, course_id):
    course = Course.objects.get(id=course_id)
    course.delete()

    return redirect('/course/')

story4/templates/story4/about.html
{% extends 'story4/template.html' %}

{% load static %}

{% block title %}Kevin Dharmawan - About{% endblock title %}
{% block nav-about %}active{% endblock nav-about %}

{% block add-style %}
{% endblock add-style %}

{% block content %}
<div class="d-flex flex-column justify-content-center">

    <div style="height: 200px;"></div>

    <div class="d-flex flex-row justify-content-center align-items-center">
        <div>
            <img id="aboutpic" src="{% static 'story4/images/aboutpic.jpg' %}">
        </div>
        <div class="justify-content-center">
            <div style="width: 450px; margin-left: 50px; margin-top: auto; margin-bottom: auto; text-align: left;">
                <h3 style="color: coral; word-wrap: break-word;">
                    Hi, I’m Kevin, a  Computer Science student from University of Indonesia
                </h3>
                <p style="word-wrap: break-word;">
                    I have no prior knowledge to programming when I decided to
                    major in Computer Science. The only thing I knew was it’s cool
                    and makes a lot of money and now i think it’s one of the best
                    decision i’ve made.<br>
                    I always love to learn new things, especially things within my
                    area of interest that I mentioned in the “home” page. I also like
                    to do brain-consuming activity for fun, like doing puzzles or
                    playing Rubik’s cube.
                </p>
            </div>
        </div>
    </div>

    <div id="separator"></div>

    <div class="justify-content-center" style="text-align: center;">
        <h3 style="color: coral; margin-bottom: 30px;">education.</h3>
        <img style="width: 80%;" src="{% static 'story4/images/education.png' %}">
    </div>

    <div id="separator"></div>

    <div class="d-flex flex-column justify-content-center">
        <div>
            <h3 class="middle" style="color: coral; margin-bottom: 30px;">currently learning.</h3>
        </div>
        <div class="d-flex flex-row justify-content-md-center">
            <div>
                <img class="learn" src="{% static 'story4/images/learn-1.jpg' %}">
                <h4 style="color: coral; text-align: center;">video editing</h4>
            </div>
            <div>
                <img class="learn" src="{% static 'story4/images/learn-2.jpg' %}">
                <h4 style="color: coral; text-align: center;">stock analysis</h4>
            </div>
            <div>
                <img class="learn" src="{% static 'story4/images/learn-3.jpg' %}">
                <h4 style="color: coral; text-align: center;">web development</h4>
            </div>
        </div>
    </div>

    <div id="separator"></div>

    <h3 style="color: coral; margin-bottom: 30px; text-align: center;">accordion.</h3>
    <div class="d-flex flex-column w-50" style="margin-left: auto; margin-right: auto;">
        <div class="accordion">
            <div class="d-flex flex-row">
                <div class="mr-auto">
                    <p>Fun Facts About Me</p>
                </div>
                <div>
                    <p class="up-button">&#9650</p>
                </div>
                <div>
                    <p class="down-button">&#9660</p>
                </div>
            </div>
            <div class="accordion-content">
                <p>
                    1. I can solve Rubik's Cube in under a minute<br>
                    2. I'm in a national magazine in my first year on Earth<br>
                    3. I've mastered sixth grade math and science on second grade<br>
                </p>
            </div>
        </div>
        <div class="accordion">
            <div class="d-flex flex-row">
                <div class="mr-auto">
                    <p>Lockdown Activities</p>
                </div>
                <div>
                    <p class="up-button">&#9650</p>
                </div>
                <div>
                    <p class="down-button">&#9660</p>
                </div>
            </div>
            <div class="accordion-content">
                <p>
                    1. Online class, obviously<br>
                    2. Watch Tiktok videos<br>
                    3. Gaming with the boys<br>
                    3. Learning personal finance<br>
                </p>
            </div>
        </div>
        <div class="accordion">
            <div class="d-flex flex-row">
                <div class="mr-auto">
                    <p>Games I Like</p>
                </div>
                <div>
                    <p class="up-button">&#9650</p>
                </div>
                <div>
                    <p class="down-button">&#9660</p>
                </div>
            </div>
            <div class="accordion-content">
                <p>
                    1. Minecraft<br>
                    2. GTA V<br>
                    3. Roblox<br>
                    4. Pokemon<br>
                    5. Cities Skylines<br>
                </p>
            </div>
        </div>
        <div class="accordion">
            <div class="d-flex flex-row">
                <div class="mr-auto">
                    <p>Organization and Achievement</p>
                </div>
                <div>
                    <p class="up-button">&#9650</p>
                </div>
                <div>
                    <p class="down-button">&#9660</p>
                </div>
            </div>
            <div class="accordion-content">
                <p>
                    Nothing because I'm a piece of sh*t.
                </p>
            </div>
        </div>
    </div>

    <div id="separator"></div>
</div>



<div class="d-xl-flex" style="height: 60px; margin-top: 100px;">
    <div class="middle">
        <a href="https://www.instagram.com/kevindharmawan2002/">
            <img class="contact" src="{% static 'story4/icons/instagram.png' %}" style="border-radius: 50%;">
        </a>
        <a href="https://www.facebook.com/kevin.dharmawan.9/">
            <img class="contact" src="{% static 'story4/icons/facebook.png' %}">
        </a>
        <a href="https://www.linkedin.com/in/kevin-dharmawan-0363151a0/">
            <img class="contact" src="{% static 'story4/icons/linkedin.png' %}">
        </a>
        <a href="mailto: kevin.dharmawan@ui.ac.id">
            <img class="contact" src="{% static 'story4/icons/gmail.png' %}">
        </a>
    </div>
</div>

{% endblock content %}

story4/templates/story4/addcourse.html
{% extends 'story4/template.html' %}

{% load static %}

{% block title %}Kevin Dharmawan - Course{% endblock title %}
{% block nav-course %}active{% endblock nav-course %}

{% block add-style %}
#id_name, #id_initial, #id_lecturer, #id_credit, #id_description, #id_year, #id_difficulty, #id_room {
    width: 400px;
}
{% endblock add-style %}

{% block content %}


<div class="container">
    <div class="row" style="height:150px;"></div>
    <div class="row justify-content-center">
        <h2 style="color: coral; padding: 30px;">add course</h2>
    </div>
    <div class="row justify-content-center">
        <div class="table-responsive-lg">
            <form action="" method="POST">
            <table class="table">
                <tbody>
                    {{ form.as_table }}
                    <tr>
                        <th></th>
                        <td>
                            {% csrf_token %}
                            <input class="btn btn-primary" type="submit" value="Add Course" style="padding-right: 50px; padding-left: 50px;">
                        </td>
                    </tr>
                </tbody>
            </table>
            </form>
        </div>
    </div>
    <div class="row" style="height: 150px;"></div>
</div>


{% endblock content %}

story4/templates/story4/blog.html
{% extends 'story4/template.html' %}

{% load static %}

{% block title %}Kevin Dharmawan - Blog{% endblock title %}
{% block nav-blog %}active{% endblock nav-blog %}

{% block content %}
<div class="container-fluid justify-content-center" style="padding-top: 12%;">
    <h2 class="middle" style="color: coral;">my story</h2>
</div>

<div>
    <div class="d-md-flex justify-content-center">
        <div class="d-flex justify-content-center blog">
            <div>
                <img class="blogpic" src="{% static 'story4/images/blog-1.jpg' %}">
                <h4 class="blogtitle">Blog Title Here</h4>
                <p class="blogdate">03 Oct 2020</p>
                <p class="highlights">
                    write blog highlights sentences, most significant paragraph or sentence, opening paragraph,
                    or clickbait paragraph or sentence
                </p>
            </div>
        </div>
        <div class="d-flex justify-content-center blog">
            <div>
                <img class="blogpic" src="{% static 'story4/images/blog-2.jpg' %}">
                <h4 class="blogtitle">Blog Title Here</h4>
                <p class="blogdate">02 Oct 2020</p>
                <p class="highlights">
                    write blog highlights sentences, most significant paragraph or sentence, opening paragraph,
                    or clickbait paragraph or sentence
                </p>
            </div>
        </div>
        <div class="d-flex justify-content-center blog">
            <div>
                <img class="blogpic" src="{% static 'story4/images/blog-3.jpg' %}">
                <h4 class="blogtitle">Blog Title Here</h4>
                <p class="blogdate">01 Oct 2020</p>
                <p class="highlights">
                    write blog highlights sentences, most significant paragraph or sentence, opening paragraph,
                    or clickbait paragraph or sentence
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

story4/templates/story4/course.html
{% extends 'story4/template.html' %}

{% load static %}

{% block title %}Kevin Dharmawan - Course{% endblock title %}
{% block nav-course %}active{% endblock nav-course %}

{% block content %}


<div class="container">
    <div class="row" style="height:150px;"></div>
    <div class="row justify-content-center">
        <h1 style="color: coral; padding: 30px;">my courses</h1>
    </div>

    {% if courses %}

    <div class="row">
        <div class="col-xl justify-content-center">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">Course</th>
                        <th scope="col">Credit</th>
                        <th scope="col">Lecturer</th>
                        <th scope="col">Detail</th>
                        <th scope="col">Delete</th>
                    </tr>
                </thead>
                <tbody>
        
                {% for course in courses %}
        
                    <tr>
                        <th scope="row">{{ course.initial }}</th>
                        <td>{{ course.credit }}</td>
                        <td>{{ course.lecturer }}</td>
                        <td>
                            <form action="/detailcourse/{{ course.id }}" method="GET" style="display: inline;">
                                {% csrf_token %}
                                <input class="btn btn-primary" type="submit" value="Detail">
                            </form>
                        </td>
                        <td>
                            <form action="/deletecourse/{{ course.id }}" method="POST" style="display: inline;">
                                {% csrf_token %}
                                <input class="btn btn-danger" type="submit" value="Delete">
                            </form>
                        </td>
                    </tr>
        
                {% endfor %}
        
                </tbody>
            </table>
        </div>
    </div>

    {% endif %}
    
    <div class="row justify-content-center">
        <a class="btn btn-success" style="padding-left: 50px; padding-right: 50px;" href= "{% url 'story4:addcourse' %}">Add Course</a>
    </div>
    <div class="row" style="height: 150px;"></div>

</div>


{% endblock content %}

story4/templates/story4/detailcourse.html
{% extends 'story4/template.html' %}

{% load static %}

{% block title %}Kevin Dharmawan - Course{% endblock title %}
{% block nav-course %}active{% endblock nav-course %}

{% block content %}


<div class="container">
    <div class="row" style="height:150px;"></div>
    <div class="row justify-content-center">
        <h2 style="color: coral; padding: 30px;">course detail</h2>
    </div>
    <div class="row justify-content-center">
        <div class="table-responsive-lg" style="width: 500px;">
            <table class="table">
                <tbody>
                    <tr>
                        <th>Name:</th>
                        <td>{{ course.name }}</td>
                    </tr>
                    <tr>
                        <th>Lecturer:</th>
                        <td>{{ course.lecturer }}</td>
                    </tr>
                    <tr>
                        <th>Credit:</th>
                        <td>{{ course.credit }}</td>
                    </tr>
                    <tr>
                        <th>Difficulty:</th>
                        <td>{{ course.difficulty }}</td>
                    </tr>
                    <tr>
                        <th>Description:</th>
                        <td>{{ course.description }}</td>
                    </tr>
                    <tr>
                        <th>Year:</th>
                        <td>{{ course.year }}</td>
                    </tr>
                    <tr>
                        <th>Room:</th>
                        <td>{{ course.room }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row" style="height: 150px;"></div>
</div>


{% endblock content %}

story4/templates/story4/index.html
{% extends 'story4/template.html' %}

{% load static %}

{% block title %}Kevin Dharmawan - Home{% endblock title %}
{% block nav-home %}active{% endblock nav-home %}

{% block content %}
<div class="container-fluid home-greetings">
    <div class="middle" style="color: white; margin: 0;">

        {% if user.is_authenticated %}
        <h1>Hey {{ user.first_name }}! It's me, Kevin.</h1>
        {% else %}
        <h1>Hey there! It's me, Kevin.</h1>
        {% endif %}

        <h2>welcome to my website</h2>
    </div>
</div>
<div class="container-fluid page">
    <div class="middle">
        <img id="homepic" class="rounded-circle" src="{% static 'story4/images/homepic.jpg' %}">
        <div style="width: 400px; margin-left: auto; margin-right: auto;">
            <h2 style="color: coral; margin: 10px;">hello.</h2>
            <p style="word-wrap: break-word;">
                I love to do things that involved analysis and creativity. I spent
                an excessive amount of time learning design, technology, architecture
                language, economy, finance, history, health, and psychology.
            </p>
        </div>
    </div>
</div>
<div class="d-xl-flex" style="height: 110%;">
    <div class="middle">
        <h2 style="color: coral; margin-bottom: 30px;">things i like.</h2>
        <table class="skill" style="margin-left: auto; margin-right: auto;">
            <tr>
                <td><img id="skillpic" style="border-color: hotpink;" src="{% static 'story4/images/skill-1.jpg' %}"></td>
                <td>
                    <h3 style="color: hotpink;">graphic design</h3>
                    <h5>
                        this is one of a few skills i learned<br>
                        during quarantine because it can<br>
                        complement my other hobbies.
                    </h5>
                </td>
            </tr>
            <tr>
                <td><img id="skillpic" style="border-color: rebeccapurple;" src="{% static 'story4/images/skill-2.jpg' %}"></td>
                <td>
                    <h3 style="color: rebeccapurple;">personal finance</h3>
                    <h5>
                        i started to learn about personal<br>
                        finance at such a young age - seven<br>
                        years old, to be exact.
                    </h5>
                </td>
            </tr>
            <tr>
                <td><img id="skillpic" style="border-color: crimson;" src="{% static 'story4/images/skill-3.jpeg' %}"></td>
                <td>
                    <h3 style="color: crimson;">game development</h3>
                    <h5>
                        it was my childhood dream to be able<br>
                        to make my own game, i do world<br>
                        design a lot in my spare time.
                    </h5>
                </td>
            </tr>
            <tr>
                <td><img id="skillpic" style="border-color: cornflowerblue;" src="{% static 'story4/images/skill-4.jpg' %}"></td>
                <td>
                    <h3 style="color: cornflowerblue;">body language</h3>
                    <h5>
                        i find it very useful to have the ability<br>
                        to read other's mind from the way they<br>
                        walk to the way they talk.
                    </h5>
                </td>
            </tr>
        </table>
    </div>
</div>

<div class="d-xl-flex" style="height: 60px; margin-top: 70px;">
    <div class="middle">
        <a href="https://www.instagram.com/kevindharmawan2002/">
            <img class="contact" src="{% static 'story4/icons/instagram.png' %}" style="border-radius: 50%;">
        </a>
        <a href="https://www.facebook.com/kevin.dharmawan.9/">
            <img class="contact" src="{% static 'story4/icons/facebook.png' %}">
        </a>
        <a href="https://www.linkedin.com/in/kevin-dharmawan-0363151a0/">
            <img class="contact" src="{% static 'story4/icons/linkedin.png' %}">
        </a>
        <a href="mailto: kevin.dharmawan@ui.ac.id">
            <img class="contact" src="{% static 'story4/icons/gmail.png' %}">
        </a>
    </div>
</div>
{% endblock content %}

story4/templates/story4/portfolio.html
{% extends 'story4/template.html' %}

{% load static %}

{% block title %}Kevin Dharmawan - Portfolio{% endblock title %}
{% block nav-portfolio %}active{% endblock nav-portfolio %}

{% block add-style %}
body {
    background-image: url("{% static 'story4/images/background-portfolio.png' %}");
    background-attachment: fixed;
    background-position: center;
    background-repeat: no-repeat;
}
{% endblock add-style %}

{% block content %}
<div class="container-fluid page">
    <div class="middle" style="color: white; margin: 0;">
        <h1>this is my portfolio</h1>
        <h3>scroll down to see some amazing works</h3>
    </div>
</div>

<div class="container-fluid page">
    <div class="middle">
        <h2 style="color:white">mobile apps design</h2>
        <img src="{% static 'story4/images/portfolio-1.png' %}" style="width: 80%;">
    </div>
</div>

<div class="container-fluid page">
    <div class="middle">
        <h2 style="color:white; margin-bottom: 50px;">unknown game</h2>
        <img src="{% static 'story4/images/portfolio-2.png' %}" style="width: 80%;">
    </div>
</div>

<div class="container-fluid page">
    <div class="middle">
        <h2 style="color:white; margin: -20px;">custom card deck</h2>
        <img src="{% static 'story4/images/portfolio-3.png' %}" style="width: 80%;">
    </div>
</div>

<div class="container-fluid page">
    <div class="middle">
        <h2 style="color:white">and...</h2>
    </div>
</div>

<div class="container-fluid page">
    <div class="middle">
        <h2 style="color:white">this website.</h2>
    </div>
</div>
{% endblock content %}

story4/templates/story4/template.html
<!DOCTYPE html>
<html>

{% load static %}

    <head>
        <title>{% block title %}{% endblock title %}</title>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'story4/style.css' %}">

        <style>
            {% block add-style %}
            {% endblock add-style %}
        </style>
    </head>

    <body>
        <nav class="navbar fixed-top navbar-expand-lg navbar-light" style="padding: 0;">
            <a class="navbar-brand my-nav-item">Kevin Dharmawan</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item {% block nav-home %}{% endblock nav-home %} my-nav-item">
                        <a class="nav-link" href="{% url 'story4:index' %}">Home</a>
                    </li>
                    <li class="nav-item {% block nav-portfolio %}{% endblock nav-portfolio %} my-nav-item">
                        <a class="nav-link" href="{% url 'story4:portfolio' %}">Portfolio</a>
                    </li>
                    <li class="nav-item {% block nav-blog %}{% endblock nav-blog %} my-nav-item">
                        <a class="nav-link" href="{% url 'story4:blog' %}">Blog</a>
                    </li>
                    <li class="nav-item {% block nav-about %}{% endblock nav-about %} my-nav-item">
                        <a class="nav-link" href="{% url 'story4:about' %}">About</a>
                    </li>
                    <li class="nav-item {% block nav-course %}{% endblock nav-course %} my-nav-item">
                        <a class="nav-link" href="{% url 'story4:course' %}">Course</a>
                    </li>
                    <li class="nav-item my-nav-item">
                        <a class="nav-link" href="{% url 'story1:index' %}">Story 1</a>
                    </li>
                    <li class="nav-item {% block nav-story6 %}{% endblock nav-story6 %} my-nav-item">
                        <a class="nav-link" href="{% url 'story6:index' %}">Story 6</a>
                    </li>
                    <li class="nav-item {% block nav-story8 %}{% endblock nav-story8 %} my-nav-item">
                        <a class="nav-link" href="{% url 'story8:index' %}">Story 8</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item my-nav-item">
                        <a class="nav-link" href="{% url 'story9:logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item my-nav-item">
                        <a class="nav-link" href="{% url 'story9:index' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        {% block content %}
        {% endblock content %}

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> 
        <script src="{% static 'story4/script.js' %}"></script>

        {% block script %}
        {% endblock script %}
    </body>
</html>